[package]
name = "chip_8"
version = "0.1.0"
authors = ["Eric Nowac"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
sfml = "0.14.0"